ActorUI.Web/Models/CarInsuranceViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Broker.Domain.Models;
using Newtonsoft.Json;

namespace ActorUI.web.Models
{
    public class CarInsuranceViewModel
    {
        public IEnumerable<SelectListItem> Counties { get; set; }

        public IEnumerable<SelectListItem> NoClaimsBonusList { get; set; }

        public CarQuoteRequestDto CarQuoteRequest { get; set; }

        public string JsonVehicle { get; set; }

        public VehicleDetailsDto Vehicle
        {
            get { return JsonVehicle != string.Empty ? 
                JsonConvert.DeserializeObject<VehicleDetailsDto>(JsonVehicle) : 
                new VehicleDetailsDto(); }
        }     

        [Required]
        public string CarValue { get; set; }
    }
}

ActorUI.Web/Models/QuotesReturnedViewModel.cs
using System.Collections.Generic;
using Broker.Domain.Models;

namespace ActorUI.web.Models
{
    public class QuotesReturnedViewModel
    {
        public IEnumerable<CarQuoteResponseDto> Quotes { get; set; } 
    }
}

ActorUI.Web/Controllers/CarInsuranceController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using ActorUI.Actors;
using ActorUI.Actors.Messages;
using ActorUI.web.Configuration;
using ActorUI.web.ModelBuilders;
using ActorUI.web.Models;
using Akka.Actor;
using Broker.Domain.Models;

namespace ActorUI.Web.Controllers
{
    public class CarInsuranceController : Controller
    {

        private readonly static NLog.Logger _logger = NLog.LogManager.GetCurrentClassLogger();

        private readonly ICarInsuranceModelBuilder _carInsuranceModelBuilder;
        private readonly ISystemConfiguration _systemConfiguration;


        public CarInsuranceController(ICarInsuranceModelBuilder carInsuranceModelBuilder, 
                                        ISystemConfiguration systemConfiguration)
        {
            _systemConfiguration = systemConfiguration;
            _carInsuranceModelBuilder = carInsuranceModelBuilder;
        }

        // GET: /CarInsurance/
        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                var model = _carInsuranceModelBuilder.BuildCarQuoteView();
                return View(model);
            }
            catch (Exception e)
            {
                Trace.TraceError(e.ToString());
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(CarInsuranceViewModel model)
        {
            try
            {
                decimal value;
                decimal.TryParse(model.CarValue, out value);

                model.CarQuoteRequest.VehicleValue = value;
                model.CarQuoteRequest.VehicleRef = model.Vehicle.VehicleRef;

                // populate the database & query the external services for quotes
                var quoteRequestMsg = new RequestQuotes(model.CarQuoteRequest, model.Vehicle,
                                                                                _systemConfiguration.ServicesBaseUri);
                model.CarQuoteRequest.CarQuoteId = await SystemActors.QuoteActor.Ask<int>(quoteRequestMsg);

            }
            catch (Exception e)
            {
                _logger.Error(e.ToString());
            }

            return RedirectToAction("Details", new {id = model.CarQuoteRequest.CarQuoteId});
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            // Sit here for a max of n seconds and wait for the quote results to be persisted 
            for (int i = 0; i < 15; i++)
            {
                Thread.Sleep(1000);
                bool isPersistedSuccessfully = await SystemActors.QuoteActor.Ask<bool>(new IsLoadComplete());
                if (isPersistedSuccessfully)
                    break;
            }
          
            var quotes = await SystemActors.QuoteActor.Ask<IEnumerable<CarQuoteResponseDto>>(new ListQuotes(id));

            return View(new QuotesReturnedViewModel{ Quotes = quotes});
        }


        [HttpGet]
        public async Task<JsonResult> CheckCar(string regNo)
        {
            try
            {
                _logger.Trace("Find Car Registration {0}", regNo);
                VehicleDetailsDto car = null;

                // check local storage
                car = await SystemActors.VehicleActor.Ask<VehicleDetailsDto>(new FindCarFromLocalStorage(regNo));
                if (car == null)
                {
                    car = await SystemActors.VehicleActor.Ask<VehicleDetailsDto>(new FindCarFromService(regNo, _systemConfiguration.CarFinderBaseUri));
                    // async write to the Db fire & froget
                    SystemActors.VehicleActor.Tell(new SaveVehicleDetails(car)); 
                }
                   
                return Json(car, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return Json(new { id = -1, msg = e.Message }, JsonRequestBehavior.AllowGet);
            }
        }
	}
}

ActorUI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ActorUI.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ActorUI.Web/Views/CarInsurance/Details.cshtml
@using System.Globalization
@model ActorUI.web.Models.QuotesReturnedViewModel
@{
    ViewBag.Title = "Car Insurance Quick Quote";
}

<h2>Quotes Returned <small>Cheapest are highlighted.</small></h2>

<div class="row" align="right"><a href="@Url.Action("Index", "CarInsurance")" class="btn btn-sm btn-default">Search Again!</a></div>

<div class="col-md-4">
    <h4>Comprehensive</h4>
</div>

<div class="col-md-4">
    <h4>Third Party (Fire & Theft)</h4>
</div>

<div class="col-md-4">
    <h4>Third Party</h4>
</div>

@foreach (var quote in @Model.Quotes)
{
    <div class="col-md-4">
        <div class="@(quote.IsCheapest.HasValue && quote.IsCheapest.Value ? "alert alert-success" : "alert alert-warning")">
            <table>
                <tr>
                    <td style="width: 100px;">Insurer:</td>
                    <td>@quote.Insurer</td>
                </tr>
                <tr>
                    <td>Cover:</td>
                    <td>@quote.QuoteType</td>
                </tr>
                <tr>
                    <td>Cost:</td>
                    <td>@String.Format(CultureInfo.CurrentCulture, "{0:C}", @quote.QuoteValue)</td>
                </tr>
            </table>
        </div>
    </div>
}

ActorUI.Web/Views/CarInsurance/Index.cshtml
@model ActorUI.web.Models.CarInsuranceViewModel
@{
    ViewBag.Title = "Car Insurance Quick Quote";
}

<h2>Quick Quote (using Actors)</h2>

<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" action="@Url.Action("CheckCar", "CarInsurance")" method="GET" id="check-reg" data-parsley-validate="true">
            <div class="form-group">
                <label class="col-md-3 control-label">Car Registration</label>
                <div class="col-md-3">
                    <input type="text" class="form-control" id="regNo" autocomplete="off" required autofocus style="text-transform: uppercase" placeholder="151-D-123456" />
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-md-3 control-label"></label>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-sm btn-success">Find My Car</button>
                    <i id="spinner" class="fa fa-2x fa-spinner fa-spin" style="display: none;"></i>
                </div>
            </div>   
            
            <div id="carFinderResults" style="display: none">               
                                  
            </div>                   
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-12">     
          <form class="form-horizontal" action="@Url.Action("Create", "CarInsurance")" method="POST" id="create-job" data-parsley-validate="true">
              @Html.HiddenFor(x => x.JsonVehicle)
              <div class="form-group">
                  <label class="col-md-3 control-label">Area Kept</label>
                  <div class="col-md-3">
                      @Html.DropDownListFor(x => x.CarQuoteRequest.CountyId, Model.Counties, "-- Select County--", new { @class = "form-control", @required="true" })
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-md-3 control-label">No Claims Discount</label>
                  <div class="col-md-3">
                      @Html.DropDownListFor(x => x.CarQuoteRequest.NoClaimsDiscountYears, Model.NoClaimsBonusList, "-- Select Discount--", new { @class = "form-control", @data_parsley_required="true" })    
                      @Html.ValidationMessageFor(x => x.CarQuoteRequest.NoClaimsDiscountYears)
                  </div> 
              </div>
              
              <div class="form-group">
                  <label class="col-md-3 control-label">Vehicle Value (€)</label>
                  <div class="col-md-3">
                      @Html.TextBoxFor(x => x.CarValue, new { @class = "form-control", @autocomplete = "off", @placeholder = "€", @data_parsley_required = "true" })
                      @Html.ValidationMessageFor(x => x.CarValue)
                  </div>
              </div>

              <div class="form-group">
                  <label class="col-md-3 control-label">Your Age</label>
                  <div class="col-md-3">
                      @Html.TextBoxFor(x => x.CarQuoteRequest.DriverAge, new { @class = "form-control", @autocomplete = "off", @data_parsley_type = "number", @data_parsley_required = "true", @placeholder="Drivers Age" })
                      @Html.ValidationMessageFor(x => x.CarQuoteRequest.DriverAge)
                  </div>
              </div>
              
              <div class="form-group">
                  <label class="col-md-3 control-label">Email</label>
                  <div class="col-md-3">
                      @Html.TextBoxFor(x => x.CarQuoteRequest.EmailAddress, new { @class = "form-control", @autocomplete = "off", @data_parsley_type="email", @required="true", @placeholder="Email Address" })
                      @Html.ValidationMessageFor(x => x.CarQuoteRequest.EmailAddress)
                  </div>
              </div>
              
              <div class="form-group">
                  <label class="col-md-3 control-label">Phone Number</label>
                  <div class="col-md-3">
                      @Html.TextBoxFor(x => x.CarQuoteRequest.Telephone, new { @class = "form-control", @autocomplete = "off", @data_parsley_type = "digits", @required = "true", @placeholder="Contact No." })
                      @Html.ValidationMessageFor(x => x.CarQuoteRequest.Telephone)
                  </div>
              </div>

              <div class="form-group">
                        <label class="col-md-3 control-label"></label>
                        <div class="col-md-3">
                            <button type="submit" class="btn btn-sm btn-primary m-r-5">Get Quick Quote!</button>
                        </div>
                    </div>
           </form>           
    </div>
</div>

@section scripts
{
    <!-- corresponding js -->
    <script src="~/Scripts/views/CarInsurance/index.js" type="text/javascript"></script>
}

ActorUI.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ActorUI.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ActorUI.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ActorUI.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quick Quote</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Some Sort of Quick Quote</p>
        </footer>
    </div>
</body>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/plugins")
@RenderSection("scripts", required: false)

</html>